apiVersion: v1
kind: ConfigMap
metadata:
  name: bookshop-config
  labels:
    db: bookshop-postgres
data:
  init.sql: |
    CREATE DATABASE bookshop_catalog;
    CREATE DATABASE bookshop_order;
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookshop-postgres
  labels:
    db: bookshop-postgres
spec:
  selector:
    matchLabels:
      db: bookshop-postgres
  template:
    metadata:
      labels:
        db: bookshop-postgres
    spec:
      containers:
        - name: bookshop-postgres
          image: postgres:14.4
          env:
            - name: POSTGRES_USER
              value: user
            - name: POSTGRES_PASSWORD
              value: password 
            - name: POSTGRES_DB
              value: bookshop_catalog
          resources:
            requests:
              cpu: 100m
              memory: 60Mi
            limits:
              cpu: 200m
              memory: 120Mi

---

apiVersion: v1
kind: Service
metadata:
  name: bookshop-postgres
  labels:
    db: bookshop-postgres
spec:
  type: ClusterIP
  selector:
    db: bookshop-postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432